####

entrezid <- c('51287')

seq.uk <- c('TTTTCACATTCCCCGCCCCTTCCGTGTGCACGCTCCCCACGAGGGGCTGGTTCCTGAAAGGATGTACAGA
GGATCCCCAACCGCCTGCGAAACCCAAGCCGCCGCGTAGGAGCGTGCGTTCGGGCCCTCTTCTCCCACCT
      GTTCGGTGAGCATCGCGTACCGCGTTCTTCAGGAGGCGTTGCGGGCACAACGGGGCTGCGATCAGCGGCC
      GCGCGCGCGCATGCGTCCTCAAAGTTCAAAGTCCTCGATACGCCTGAGGCGCCTCAGGCCTCGTGGCTGC
      CAGCATTTTTCTGCTTTAAGATCCTTTCCATGACTTCCTTGTTTAGGCCAGCCTCCACGATCCAGCTGCC
      AACCATCTAGCCTACCCTGATCTCTGAGCAGGGGTCGTCGTCATTTTACTCCAGAGGAGACTGAAGCCAA
      AAGGTGGTGAGAGGAGAGTACAGCAGCATTTACTGAGTCCTATAGTAGCCCAAGCGCTTTTCATTCGTTA
      TATTAATCTTCATTCTAATTGTGCGAATTAAATATTATTAATGGGAAAACTAAAATGAAAAAGATTACAT
      AGTAAGGCGTAGTGCTGGGATTTGAACACGGATCTCTTGGTTTAGGATCAAGGCACTTTCTATTCCACTG
      TTCTTTCTCTAAATTATTTGCTCCTGGCCCTATTTAAAGAGTTAACAGTGTATTTAGGAAGAGAAAACTA
      TCATTTATTGAACTCTTTAGACATACCAGCCTCCTTACAAACCTTACCTTTTTTTTTTTCTTTTTTTTTT
      TTTTTGAGACAGGGTCTCCCGCTGTAACCCAGGCTGGAATGCAGTGGCGTGATCACGGCTCACAGTGTTG
      CCCAGGCTGGGCGCAAACCATCCTCCCGCCTCAGCCTCCCAGTGTTGGGATTACAGGCGTGAGCCATGGC
      ACCCGGCTTCATCTCTGTGCTTCCAGAGAGGTTATTAAATGATGTGTCCAAGGGCACCAAATGAGGCAGT
      GACAAAGCTAGGTCCAAGTCTGTTTCAAAGCCCATTTTCTCCCTCTTGCTTAAGTTATACCGCCTCCAAG
      GCAAATGAGTTGTGTAAAGTGCCTAACTCCCTCTTGTGATTCCCCATTGCCCTCAGAATAAAAAGTCTTA
      AACTCCCTACTATGTCCTACAAAGCCTTGTGATGATCACTTACTTATATCGCCAGTTTAATATTGTCTTA
      TTCTCACACTGTATTCTCCCATCACTGAACTTTTTTTTTTTTTTGCTCTCATGTGTCAGATTCTATCTCA
      ACCACCTGCTCTTCCATTGACCAAAAATAGTTTTCCCATCTCTGGCTAACTTCTGTTCCATCTGTCAAGT
      TTCAGCTTGGAAATCACTTCCTCTAGGAAGCCTTCCCTGCCTATTCCTGCCCTTGTCTGGATTAGGCATC
      CCTCCACTGTGGTCCCAGTCTTTGCTATCTGTACACTGTGTAGTAAACTGCCCTGTTTCCTTGTCTAGGT
      TGTAAACTCCATGAAGCCAGGAACTTAACTGACTTAGACAGTCTTGAATCCTCAGCACTAGCATAGTGCC
      TGGTACATGATAGGTACTTAATCATTTGTTGAGTGAATGAGAGACACAGTTAAGGCAATAAGGAGTCCTA
      GTTGCTTTACAGCCCATCATGGTGAAATTTTTGCAAAGGCTGAAGTCATTTCTCTTCAAACCTTAAGTTC
      CTTCTGTATGCTGCTTTCTGCTGAGTGTTCTGATGCAGACGGGCAAGACAGTTTGGGCAAATAAATACAC
      CTCACATTTTTGTATAGTTTACAAAGCCATCTCACCTTATAGACCCAGAGGCCAGGTTTCTGCATACTGT
      ATGCTACAGCCACAGTGAACTCTTTCCATCCTTCCCATGTGTCAAAACCTACCCATATTTGGGCACTCTT
      TCACTTTGTTTGTTTGTTTGTTTTGGAGATGGAGTCTCACTCTGTCACCCAGGCTGGAGTGCAGTGGCAC
      GATCTTTGGCTCACTACAACCTCCGCCCCTTGGGTTAAAGCGATTCTCCTGCCTGAGCCTCCCGAGTAGC
      TGGGATTACAGGTGCCTGCCATCACGCCCGCCTAATTTTTGTATTTTTAGTAGAGACGGGGTTTCATCAT
      CCCGGCCAGGCTGGTCTTGAACTTCTGACCTTATGATCCATCTGCCTCGGGCTCCCAAATTGCTGGGATT
      ACATGTGTGAGCCACTGCACCCAGCCTCTTTCACTTTTTAAACTTTGTTCTTCAGCATAGAATAAGGCTA
      GTAGGATAAAAGAAGAAAGGTTATTTATTTGAAACAGGGTCTCACTATGTCACCTAAGCTGGAGTACAGT
      GGCACCATCATAGCTCACTGCAGCCTTTGAACTCCTGGGCTCAAAGGATTCTCCCTCTTCAGCCTCTTGA
      GTACCTGGGACTACAAGTGTGTGCCACTATGCCCAGCTAATTTTTACATTTTTTTTCTTTTTTCTTTTTT
      TTTGAGATGGAGTTTTGCTCTTATTGCCCAGGCTGGAGTGCAATGGTGTGATCTCGGCTCTCCGCAACCT
      CCG')

f.string <- c('CCTCCCGAG')
f.string.l <- nchar(f.string)

ch.2.loc <- c(nchar(seq.uk))

ss.loc <- c(73876901,73870258)

pos.q <- ss.loc[1] + (ch.2.loc - 1)

my.start <- pos.q + 1
my.seq <- c('CCTCCCGAGTTCAACCTCGGCTCTCCTGCTTCAGCCTCCTGAGTAGCTGGCATTACAGGCATATGCCACCACACCTTGCTAATTTTGTATTTTTAGTAGAGACGGGTTTCTCCATGTTGGTCAGGCTGATCTTGATCTCCCGACCTCAGGTGATCCGACTGCCTCAGTCTCCCAAAGTGCTGGGATTATAGGCATGAGCCACCGTATCCAGCCATTTTTAAATTTTTTTGTAGAGATGAGGTCTTGCTATTACCCCTGCTGGTCTCAAATTCCTGGGCTCAAGGGATCTTCCTGCCTCAGCCTCCCATAATGCTAGGATTACAGGTGTGAGCCATCGTACCTAGCTGAAAGTTTAGTTCTTTTTAGGTAGATCAGAGATAGCTTATCTAAAAAGATGACATTTCACCTAATTCATATTCCAATAGCAAAATCCACTGAGCTTATTGAATGTTATGTCAAGCATTCTCACAGTTTATCTCATTCAGTTCAAACCACTTTTCAGGCCTGCTCTCAGCCAGGCCTAGTGCTGGGGGCACAAAGGTAAATCAAGACGAACATCAGCCGGGCACAGTTGGCTCACACCTGTAATCCCAGCATTTTGGGTGGCTAAGGCAGGAGGATCACTTGAGCCCAGGAGTTTGAGACCATGCTGAGCAACATGGAAAAACCTTGTCTCTATTAAAGAATCAAAAAAATTAGCTGAGTGGTGATGCACACCTGTAGTCCCAGCTACTCTGGCCAGGGAGGGACTGAGGGGGAAGGATTGCTTGATCCCTAAAGATGGAGGCTACAGTGAGCCTGGGCAACAAAGCAAGACACCCTCAAAAAAAAAAAAAAAAAAACAAGCATCTGTCTTCAAGCTTAGAGTCTCCCACGGGAGACAGACACATTAAACAGGCTAAATGGTGCAGTCTGGTCAGTGCTATTTATAATTTAGGAACCTTACATATTATATCCCTACTCTAACCTGTTAATGTTCTATAGACTCCCCATCCCCAGGGACCCCAAACCACCTATCCCCAGTAGATGGCCCTGCCAAGACCAGCACCCAGCAAGATTATAGAGGAAGAAATCCTAAATGCTGGTGTGGGAGGTCTAAAACATGGGGAGAGTTTTTGGATCTGGAGTTGAGAGCCATGGGTTTGGACATGACTGGCACAAACAGCTGTCATATGTTCATGGTCAGATGTCATACATTCTCAGCTGTCTTGTTCCACCAGTATTTACCAGGAAAACAAAGAATGTGTTAAGGGATGCTCCCCCACCCCACATCTTAAGTCAGTGTGCCAAGTACTGAGATGATTTTAGGGACATTTTATTTTAAATTAAATTTACAATCTAATGGTAAATTGATTACCTAATTAGTGCCTTTCTCTTTCATCACTTGTTCTGGATGTTTCAATCAGTTTAGTGGAAGGAAAAATAAATGGGGAAACTTTTTATTCAAATATGTTTTTCTTTTGTTTTTTTGAGACAGGGTCTCTGTTGCCCAGGCTGGAGTGTGGTGGTGGAGTCAGGGCTCACTGCATCCTCAGTGGGCTCAGGCCATCCTCCCACCTCAGCCTCTCAAGTAGCTGGAACCACAGGTGTGTGCATCACC')

my.seq.len <- nchar(my.seq)     #1600



ncbi.match <- c('CCTCCCGAGTTCAACCTCGGCTCTCCTGCTTCAGCCTCCTGAGTAGCTGGCATTACAGGCATATGCC
                ACCACACCTTGCTAATTTTGTATTTTTAGTAGAGACGGGTTTCTCCATGTTGGTCAGGCTGATCTTGATC
                TCCCGACCTCAGGTGATCCGACTGCCTCAGTCTCCCAAAGTGCTGGGATTATAGGCATGAGCCACCGTAT
                CCAGCCATTTTTAAATTTTTTTGTAGAGATGAGGTCTTGCTATTACCCCTGCTGGTCTCAAATTCCTGGG
                CTCAAGGGATCTTCCTGCCTCAGCCTCCCATAATGCTAGGATTACAGGTGTGAGCCATCGTACCTAGCTG
                AAAGTTTAGTTCTTTTTAGGTAGATCAGAGATAGCTTATCTAAAAAGATGACATTTCACCTAATTCATAT
                TCCAATAGCAAAATCCACTGAGCTTATTGAATGTTATGTCAAGCATTCTCACAGTTTATCTCATTCAGTT
                CAAACCACTTTTCAGGCCTGCTCTCAGCCAGGCCTAGTGCTGGGGGCACAAAGGTAAATCAAGACGAACA
                TCAGCCGGGCACAGTTGGCTCACACCTGTAATCCCAGCATTTTGGGTGGCTAAGGCAGGAGGATCACTTG
                AGCCCAGGAGTTTGAGACCATGCTGAGCAACATGGAAAAACCTTGTCTCTATTAAAGAATCAAAAAAATT
                AGCTGAGTGGTGATGCACACCTGTAGTCCCAGCTACTCTGGCCAGGGAGGGACTGAGGGGGAAGGATTGC
                TTGATCCCTAAAGATGGAGGCTACAGTGAGCCTGGGCAACAAAGCAAGACACCCTCAAAAAAAAAAAAAA
                AAAAACAAGCATCTGTCTTCAAGCTTAGAGTCTCCCACGGGAGACAGACACATTAAACAGGCTAAATGGT
                GCAGTCTGGTCAGTGCTATTTATAATTTAGGAACCTTACATATTATATCCCTACTCTAACCTGTTAATGT
                TCTATAGACTCCCCATCCCCAGGATGTCAACCTCAGTCCCTCAAGGCCATACCTGGACCCAACGGGTGAA
                GAAAGACGATGAGGAGGAGGACCCGCTGGACCAGCTGATCTCCCGCTCTGGCTGTGCTGCCTCCCACTTT
                GCAGTGCAGGAGTGCATGGCCCAGCACCAGGACTGGCGGCAATGCCAGCCACAGGTGCAGGCGTTCAAGG
                ATTGCATGAGTGAACAGCAGGCGAGGCGGCAAGAGGAGCTGCAGAGGAGGCAAGAACAAGCCGGTGCCCA
                CCACTGAGACCCCAAACCACCTATCCCCAGTAGATGGCCCTGCCAAGACCAGCACCCAGCAAGATTATAG
                AGGAAGAAATCCTAAATGCTGGTGTGGGAGGTCTAAAACATGGGGAGAGTTTTTGGATCTGGAGTTGAGA
                GCCATGGGTTTGGACATGACTGGCACAAACAGCTGTCATATGTTCATGGTCAGATGTCATACATTCTCAG
                CTGTCTTGTTCCACCAGTATTTACCAGGAAAACAAAGAATGTGTTAAGGGATGCTCCCCCACCCCACATC
                TTAAGTCAGTGTGCCAAGTACTGAGATGATTTTAGGGACATTTTATTTTAAATTAAATTTACAATCTAAT
                GGTAAATTGATTACCTAATTAGTGCCTTTCTCTTTCATCACTTGTTCTGGATGTTTCAATCAGTTTAGTG
                GAAGGAAAAATAAATGGGGAAACTTTTTATTCAAATATGTTTTTCTTTTGTTTTTTTGAGACAGGGTCTC
                TGTTGCCCAGGCTGGAGTGTGGTGGTGGAGTCAGGGCTCACTGCATCCTCAGTGGGCTCAGGCCATCCTC
                CCACCTCAGCCTCTCAAGTAGCTGGAACCACAGGTGTGTGCATCACC')

ncbi.len <- nchar(ncbi.match)      #2290

gregexpr('GACCCCAAA',my.seq)      # found at 1001 in my sequence

gregexpr('GACCCCAAA',ncbi.match)  # found at 1555 in ncbi.match

